---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/api/v1/authenticate":
    post:
      summary: Issues an authorization token
      tags:
      - Authentication
      consumes:
      - - application/json
      produces:
      - - application/json
      parameters:
      - name: credentials
        in: body
        schema:
          type: object
          properties:
            grant_type:
              type: string
              example: client_credentials
            client_id:
              type: string
              example: "<My client id>"
            client_secret:
              type: string
              example: "<My client secret>"
          required:
          - grant_type
          - client_id
          - client_secret
      responses:
        '200':
          description: authentication successful
        '400':
          description: missing or invalid JSON
        '401':
          description: unauthorized
  "/api/v1/heartbeat":
    get:
      summary: Endpoint to determine whether or not the API is online
      tags:
      - Heartbeat
      produces:
      - application/json
      responses:
        '200':
          description: API is online
        '503':
          description: API is offline
  "/api/v1/plans":
    post:
      summary: Creates a plan
      tags:
      - Plans
      consumes:
      - application/x-www-form-urlencoded
      security:
      - http: []
      parameters:
      - name: authorization
        in: header
        type: string
      - name: json
        in: body
        schema:
          type: object
          properties:
            total_items:
              type: integer
              example: 1
            items:
              type: array
              items:
                type: object
                properties:
                  dmp:
                    type: object
                    properties:
                      title:
                        type: string
                        example: My new data management plan
                        required: true
                      description:
                        type: string
                        example: The abstract for my data management plan
                      created:
                        type: string
                        example: 2020-03-06 22:01:51 UTC
                      language:
                        type: string
                        example: en
                      ethical_issues:
                        type: boolean
                        example: true
                      ethical_issues_description:
                        type: string
                        example: A summary of any ethical concerns related to my research
                          data.
                      ethical_issues_report:
                        type: string
                        example: https://my-org.edu/path/to/my/ethical_issues_report.pdf
                      dmp_ids:
                        type: array
                        items:
                          "$ref": "#/definitions/identifier_object"
                      contact:
                        type: object
                        properties:
                          firstname:
                            type: string
                            example: John
                          surname:
                            type: string
                            example: Smith
                          mbox:
                            type: string
                            example: john.smith@nowhere.edu
                          role:
                            type: string
                            example: https://dictionary.casrai.org/Contributor_Roles/DataCuration
                          affiliations:
                            type: array
                            items:
                              "$ref": "#/definitions/affiliation_object"
                          contributor_ids:
                            type: array
                            items:
                              "$ref": "#/definitions/identifier_object"
                        required:
                        - mbox
                        - role
                      contributors:
                        type: array
                        items:
                          "$ref": "#/definitions/contributor_object"
                      project:
                        "$ref": "#/definitions/project_object"
                      extended_attributes:
                        type: array
                        items:
                          type: object
                          properties:
                            dmptool:
                              type: object
                              properties:
                                template_id:
                                  type: integer
                                  example: 123
                    required:
                    - title
                    - contact
          required:
          - total_items
          - items
      responses:
        '201':
          description: created
        '400':
          description: bad request - if JSON is invalid or Plan already exists
        '401':
          description: authorization failed - please provide your credentials
  "/api/v1/templates":
    get:
      summary: Returns the templates
      tags:
      - Templates
      consumes:
      - application/x-www-form-urlencoded
      security:
      - http: []
      parameters:
      - name: authorization
        in: header
        type: string
      responses:
        '200':
          description: success
        '401':
          description: authorization failed - please provide your credentials
securityDefinitions:
  bearerAuth:
    type: apiKey
    description: Bearer token
    name: Authorization
    in: header
definitions:
  identifier_object:
    type: object
    properties:
      type:
        enum: []
      identifier:
        type: string
        example: b7008e8f-7fdb-41b7-9d74-716b4247606a
    required:
    - type
    - identifier
  affiliation_object:
    type: object
    properties:
      name:
        type: string
        example: University of Nowhere
      abbreviation:
        type: string
        example: UN
      region:
        type: string
        example: United States
      affiliation_ids:
        type: array
        items:
          "$ref": "#/definitions/identifier_object"
    required:
    - name
  contributor_object:
    type: object
    properties:
      firstname:
        type: string
        example: Jane
      surname:
        type: string
        example: Doe
      mbox:
        type: string
        example: jane.doe@nowhere.edu
      role:
        type: string
        enum:
        - - https://dictionary.casrai.org/Contributor_Roles/Conceptualization
          - https://dictionary.casrai.org/Contributor_Roles/Data_curation
          - https://dictionary.casrai.org/Contributor_Roles/Formal_analysis
          - https://dictionary.casrai.org/Contributor_Roles/Funding_acquisition
          - https://dictionary.casrai.org/Contributor_Roles/Investigation
          - https://dictionary.casrai.org/Contributor_Roles/Methodology
          - https://dictionary.casrai.org/Contributor_Roles/Project_administration
          - https://dictionary.casrai.org/Contributor_Roles/Resources
          - https://dictionary.casrai.org/Contributor_Roles/Software
          - https://dictionary.casrai.org/Contributor_Roles/Supervision
          - https://dictionary.casrai.org/Contributor_Roles/Validation
          - https://dictionary.casrai.org/Contributor_Roles/Visualization
          - https://dictionary.casrai.org/Contributor_Roles/Writing_original_draft
          - https://dictionary.casrai.org/Contributor_Roles/Writing_review_editing
        example: https://dictionary.casrai.org/Contributor_Roles/Conceptualization
      affiliations:
        type: array
        items:
          "$ref": "#/definitions/affiliation_object"
      contributor_ids:
        type: array
        items:
          "$ref": "#/definitions/identifier_object"
    required:
    - mbox
    - role
  funding_object:
    type: object
    properties:
      name:
        type: string
        example: National Science Foundation
      funding_status:
        enum:
        - planned
        - applied
        - granted
      funder_ids:
        type: array
        items:
          "$ref": "#/definitions/identifier_object"
      grant_ids:
        type: array
        items:
          "$ref": "#/definitions/identifier_object"
    required:
    - name
    - funding_status
  project_object:
    type: object
    properties:
      title:
        type: string
        example: Study of API development in open source codebases
      description:
        type: string
        example: An abstract describing the overall research project
      start_on:
        type: string
        example: 2020-06-06 21:01:51 UTC
      end_on:
        type: string
        example: 2023-05-06 21:01:51 UTC
      funding:
        type: array
        items:
          "$ref": "#/definitions/funding_object"
    required:
    - title"
