# DMPRoadmap application config
#
#   see system.yml for infrastruture specific config (e.g. Rails, Puma, etc.)
#   see credentials.yml.enc for secrets (e.g. `EDITOR=vi rails credentials:edit`)
#
default: &default
  name: "DMPTool-Dev"
  do_not_reply_email: "do-not-reply-dmptool-dev@cdlib.org"
  helpdesk_email: "uc3@ucop.edu"

  # Uncomment the following line if you want to redirect your users to an
  # organisational contact/help page instead of using the built-in contact_us form
  contact_us_url: "https//example.org/default_contact_us_page"

  # Your organisation name, used in various places throught the application
  organisation_name: "University of California Curation Center (UC3)"
  # Your orgsanisation abbreviation
  organisation_abbreviation: "UC3"
  # Your organisation's homepage, used in some of the public facing pages
  organisation_url: "https://www.cdlib.org/"
  # Your organisation's legal (official) name - used in the copyright portion of the footer
  organisation_copywrite_name: "The Regents of the University of California"
  email_from_address: "uc3@ucop.edu"

  # Your organisation's telephone number - used on the contact us page
  organisation_phone: "+1-510-987-0555"

  # Your organisation's address - used on the contact us page
  organisation_address_line1: "University of California"
  organisation_address_line2: "Office of the President"
  organisation_address_line3: "1111 Franklin Street"
  organisation_address_line4: "Oakland, CA 94607"
  organisation_country: "USA"

  # The Google maps link to your organisation's location - used to display the
  # Google map on the contact us page.
  # To find your organisation's Google maps URL, open maps.google.com, search for
  # your orgnaisation and then click the menu link to the left of the search box,
  # once the menu opens, click the 'share or embed' link and the 'embed' tab on
  # the dialog window that opens. DO NOT place the entire <iframe> tag below, just
  # the address!
  organisation_google_maps_link: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3152.2214785789347!2d-122.26972218390863!3d37.80828097975344!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808f80b28e26ec6d%3A0x61d8b66ecd97a18c!2s415+20th+St%2C+Oakland%2C+CA+94612!5e0!3m2!1sen!2sus!4v1479338425002"

  # Used as the default domain when 'archiving' (aka anonymizing) a user account
    # for example `jane.doe@uni.edu` becomes `1234@removed_accounts-example.org`
  archived_accounts_email_suffix: "@removed_accounts_dmptool.org"

  # Available CSV separators, the default is ','
  csv_separators: [",", "|", "#"]

  # The largest page size allowed in requests to the API (all versions)
  api_max_page_size: 100

  # The link to the API documentation - used in emails about the API
  api_documentation_urls:
    v0: "https://github.com/CDLUC3/dmptool/wiki/api-v0-documentation"
    v1: "https://github.com/CDLUC3/dmptool/wiki/api-v1-documentation"

  # The link to your release notes
  release_notes_url: "https://github.com/CDLUC3/dmptool/releases"
  # The link to your issues list
  issue_list_url: "https://github.com/CDLUC3/dmptool/issues"
  # The link to your Listserv
  user_group_subscription_url: "http://listserv.ucop.edu/cgi-bin/wa.exe?SUBED1=ROADMAP-L&A=1"
  # The link to your blog
  blog_rss: "https://blog.dmptool.org/feed"

  # The links that appear on the home page. Add any number of links
  welcome_links: []

  # The default locale (use the i18n format!)
  locales_default: "en-US"
  # The character that separates a locale's ISO code for i18n. (e.g. `en-GB` or `en`)
  # Changing this value is not recommended!
  locales_i18n_join_character: "-"
  # The character that separates a locale's ISO code for Gettext. (e.g. `en_GB` or `en`)
  # Changing this value is not recommended!
  locales_gettext_join_character: "_"

  # The default user email preferences used when a new account is created
  preferences:
    email:
      users:
        new_comment: false
        admin_privileges: true
        added_as_coowner: true
        feedback_requested: true
        feedback_provided: true
      owners_and_coowners:
        visibility_changed: true

  # Determines the number of links a funder is allowed to add to their template
  max_number_links_funder: 5
  # Maximum number of links to display for an Org
  max_number_links_org: 3
  # Determines the number of links a funder can add for sample plans for their template
  max_number_links_sample_plan: 5
  # Determines the maximum number of themes to display per column when an org admin
  # updates a template question or guidance
  max_number_themes_per_column: 5
  # default results per page
  results_per_page: 10

  # The default visibility a plan receives when it is created.
  # options: 'privately_visible', 'organisationally_visible' and 'publicly_visibile'
  plans_default_visibility: "privately_visible"

  # The percentage of answers that have been filled out that determine if a plan
  # will be marked as complete. Plan completion has implications on whether or
  # not plan visibility settings are editable by the user and whether or not the
  # plan can be submitted for feedback
  plans_default_percentage_answered: 50

  # Whether or not Super adminis can read all of the user's plans regardless of
  # the plans visibility and whether or not the plan has been shared
  plans_org_admins_read_all: true

  # Whether or not Organisational administrators can read all of the user's plans
  # regardless of the plans visibility and whether or not the plan has been shared
  plans_super_admins_read_all: true

development:
  <<: *default

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default

stage:
  <<: *default

production:
  <<: *default