defaults: &defaults
  adapter: <%= ENV['DB_ADAPTER'] || 'postgresql' %>
  encoding: <%= ENV['DB_ADAPTER'] == "mysql2" ? "utf8mb4" : "" %>
  host: <%= ENV["DB_HOST"] || 'localhost' %>
  username: <%= ENV["DB_USER"] || 'root' %>
  password: <%= ENV["DB_PASSWORD"] || '' %>
  database: <%= ENV["DB_NAME"] || 'roadmap' %>
  pool: <%= ENV["DB_POOL_SIZE"] || 16 %>

development:
  <<: *defaults
  host: localhost
  username: root
  password:

test:
  <<: *defaults
  host: localhost
  username: root
  password:
  database: roadmap

stage:
  <<: *defaults

production:
  <<: *defaults
