name: Tests - MySQL

on: [push, pull_request]

jobs:
  mysql:
    runs-on: ubuntu-latest

    # Define environment variables for MySQL and Rails
    env:
      DB_ADAPTER: mysql2
      MYSQL_PWD: root
      RAILS_ENV: test

    steps:
    # Checkout the repo
    - uses: actions/checkout@v2

    # Install Ruby and run bundler
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.3
        bundler-cache: true

    # Install Node
    - uses: actions/setup-node@v2
      with:
        cache: 'yarn'

    # Copy all of the example configs over
    - name: 'Setup Default Configuration'
      run: |
        cp config/database.yml.sample config/database.yml
        cp config/initializers/contact_us.rb.example config/initializers/contact_us.rb
        cp config/initializers/wicked_pdf.rb.example config/initializers/wicked_pdf.rb

    # Stub out the Rails credentials file so that we can start the Rails app
    - name: 'Setup Credentials'
      run: EDITOR='echo "$(cat config/credentials.yml.example)" >' bundle exec rails credentials:edit

    # Set the path to the wkhtmltopdf executable
    - name: 'Determine wkhtmltopdf location'
      run: echo "WICKED_PDF_PATH=`bundle exec which wkhtmltopdf`" >> $GITHUB_ENV

    # Run yarn install for JS dependencies
    - name: 'Yarn Install'
      run: yarn install

    # Start the DB server and initialize the DB
    - name: 'Start MySQL'
      run: |
        sudo systemctl start mysql
        bin/rails db:setup RAILS_ENV=test
        bin/rails db:migrate RAILS_ENV=test

    # Prebuild the CSS, JS and image assets
    - name: 'Precompile all of the Assets'
      run: bin/rails assets:precompile

    # Run the JS tests
    - name: 'Run Karma Tests'
      run: yarn test

    # Run  the unit and functional tests
    - name: 'Run Helper and Presenter Tests'
      run: bin/bundle exec rspec spec/helpers/ spec/presenters/

    - name: 'Run Mixin and Model Tests'
      run: bin/bundle exec rspec spec/mixins/ spec/models/

    - name: 'Run Controller, Policy and View Tests'
      run: bin/bundle exec rspec spec/policies/ spec/controllers/ spec/views/

    - name: 'Run Service Tests'
      run: bin/bundle exec rspec spec/services/

    - name: 'Run Request/API Tests'
      run: bin/bundle exec rspec spec/requests/

    # Run the time consuming integration tests (using Chrome headless browser)
    - name: 'Run Rspec Integration/Feature Tests'
      run: bin/bundle exec rspec spec/features/
