name: Pa11y Accessibility Checks

on: [push, pull_request]

jobs:
  pa11y:
    runs-on: ubuntu-latest

    # Define environment variables for MySQL and Rails
    env:
      DB_ADAPTER: mysql2
      MYSQL_PWD: root
      RAILS_ENV: test

    steps:
    # Checkout the repo
    - uses: actions/checkout@v3

    # Install Ruby and run bundler
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true

    # Install Node
    - uses: actions/setup-node@v3
      with:
        node-version: '16.6.0'
        cache: 'yarn'

    # Copy all of the example configs over
    - name: 'Setup the application'
      run: |
        cp .env.mysql2 .env

    # Stub out the Rails credentials file so that we can start the Rails app
    - name: 'Setup Credentials'
      run: EDITOR='echo "$(cat config/credentials.yml.mysql2)" >' bundle exec rails credentials:edit

    # Set the path to the wkhtmltopdf executable
    - name: 'Determine wkhtmltopdf location'
      run: echo "DMPROADMAP_WKHTMLTOPDF_PATH=`bundle exec which wkhtmltopdf`" >> $GITHUB_ENV

    # Run yarn install for JS dependencies
    - name: 'Yarn Install'
      run: yarn install

    # Start the DB server and initialize the DB
    - name: 'Start MySQL'
      run: sudo systemctl start mysql

    - name: 'Build out the test database'
      run: |
        bundle exec rails db:create RAILS_ENV=test
        bundle exec rails db:schema:load RAILS_ENV=test

    - name: 'Run any pending database migrations'
      run: bin/rails db:migrate RAILS_ENV=test

    # Prebuild the CSS, JS and image assets
    - name: 'Precompile all of the Assets'
      run: bin/rails assets:precompile

    - name: 'Start up the application'
      run: bin/rails s -d

    - name: 'Run pa11y-ci tests'
      run: yarn pa11y-sitemap

    - name: 'Shut down the application'
      run: kill `cat tmp/pids/server.pid`
